version: "3.8"
services:
  nature-db:
    restart: always
    image: postgres:14.15-alpine3.20
    container_name: nature-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nature
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

